import NavBar from "@/components/layout/navbar";
import { cn } from "@/lib/utils";
import "@/public/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className={cn("gradient font-g8 overflow-y-scroll relative")}>
      <NavBar page="leaderboard" />
      {children}
    </body>
  );
}
