import { cn } from "@/lib/utils";
import NavBar from "@/components/ui/navbar";
import "@/public/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className={cn("gradient font-g8 overflow-y-scroll")}>
      <NavBar />
      {children}
    </body>
  );
}
