import { cn } from "@/lib/utils";
import NavigationMenu from "@/components/navigation-menu";
import "@/public/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className={cn("gradient")}>
      <NavigationMenu />
      {children}
    </body>
  );
}
