import { cn } from "@/lib/utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div
      className={cn(
        "lg:h-screen font-g8 overflow-y-hidden tallXS:!h-full h-full"
      )}
    >
      
      {children}
    </div>
  );
}
